### ISSUE TITLE
Terraform GCP tfvars Required inputs actually required

### ISSUE THREAD

**Issue by Celestica-Edward** [CheckPointSW/CloudGuardIaaS#104]
Per the documentation at 
https://github.com/CheckPointSW/CloudGuardIaaS/tree/master/terraform/gcp/high-availability#inputs

The input variables, "service_account_path" or "project" are "not" required, but you cannot execute with a plan that omits these variables:

If I have a tfvars with service_account_path = "" or, without service_account_path at all:

```
>terraform plan -var-file=terraform-sandbox.tfvars
random_string.generated_password: Refreshing state... [id=AxEbI9pi8L0b]

Error: Invalid function argument

  on main.tf line 2, in provider "google":
   2:   credentials = file(var.service_account_path)
    |----------------
    | var.service_account_path is ""

Invalid value for "path" parameter: failed to read ..
```

If I have no project variable:
```
Error: project: required field is not set

  on variables.tf line 32, in data "google_compute_regions" "available_regions":
  32: data "google_compute_regions" "available_regions" {
```

**Comment by chkp-arielto** [comment]
Hi @Celestica-Edward 
Thanks for notifying us.
"service_account_path" and "project" parameters are indeed required, and we'll modify them the next time we update our templates.
Thanks,
Ariel

**Comment by chkp-arielto** [comment]
Hi @Celestica-Edward 
We've modified it as you can see in https://github.com/CheckPointSW/CloudGuardIaaS/pull/120
Thanks,
Ariel
