### ISSUE TITLE
Terraform with AWS and CloudGuard Network Security for Gateway Load Balancer - BYOL

### ISSUE THREAD

**Issue by Celestica-Edward** [CheckPointSW/CloudGuardIaaS#112]
Hi,

We're looking to use terraform to deploy this marketplace solution (CloudGuard Network Security for Gateway Load Balancer - BYOL):
https://aws.amazon.com/marketplace/pp/prodview-tq2l5nyunuesu?ref_=srh_res_product_title#pdp-overview

Is this supported from the list of images available at https://github.com/CheckPointSW/CloudGuardIaaS/tree/master/terraform/aws ?

**Comment by chkp-romanka** [comment]
Hi Edward,
There is no terraform template for GWLB offer
But it is in our roadmap for 2021
Will keep you updated
