### ISSUE TITLE
Terraform providers module with count throwing error

### ISSUE THREAD

**Issue by sankargopal-77** [CheckPointSW/CloudGuardIaaS#114]
Hi,

I'm calling management module from my code , however getting below error while calling master version. It looks like providers block doesn't work with count parameter .

As we are using aws provider,  once I commented the providers block from main.tf in management module 
and removed provider block from main.tf ( cme-iam-role module) and all works fine.

Should I raise a PR or is there a fix for this.

module "cme_iam_role" {
  count                       = local.create_iam_role ? 1 : 0
  source = "../cme-iam-role"
    //providers = {
     // aws = aws
   // }

 
Error message:
**************
Module "cme_iam_role" cannot be used with count because it contains a nested
provider configuration for "aws", at
CloudGuardIaaS/terraform/aws/cme-iam-role/main.tf:1,10-15.

This module can be made compatible with count by changing it to receive all of
its provider configurations from the calling module, by using the "providers"
argument in the calling module block

**Comment by chkp-noye** [comment]
Hi,
Did you follow README instructions and mark in comment the provider block in sub-module "cme-iam-role" ?

**Comment by chkp-romanka** [comment]
@sankargopal-77 
Can you please answer on the question above?

**Comment by sankargopal-77** [comment]
Hi  @chkp-romanka ,

Yes I read the Readme instructions an commented the block but i was how i can we can call your module without making any changes locally?

**Comment by chkp-noye** [comment]
Hi @sankargopal-77 , can you please elaborate ?
Did you mark in comment the provider block in "cme_iam_role" module and you are still not able to deploy the management ?
This local change is currently required due to terraform limitations.

**Comment by chkp-romanka** [comment]
Hi @sankargopal-77 
Can you please answer on the last question?
Thanks

**Comment by sankargopal-77** [comment]
After commenting the block , I can able to deploy but ideally I would prefer to source the module  directly without make any local changes however  I do  understand the terraform limitations.

**Comment by chkp-romanka** [comment]
@sankargopal-77 
Thanks for your reply and feedback!
We will check how the template can be improved
