### ISSUE TITLE
Add support for MDS in CloudGuardIaaS/terraform/azure/

### ISSUE THREAD

**Issue by chkp-jimo** [CheckPointSW/CloudGuardIaaS#126]
Hi, 

Can you add support for creating mds-primary, mds-secondary and mds-logserver in CloudGuardIaaS/terraform/azure/?

Thanks!
Jim

**Comment by chkp-arielto** [comment]
Hi Jim, 
This implementation is in our long-term roadmap. 
I encourage you to turn on the repository notification to be alerted when we release this template.
