### ISSUE TITLE
Feature Request: Allow List of CIDR for admin_cidr in FW Management Module

### ISSUE THREAD

**Issue by ygoodmn** [CheckPointSW/CloudGuardIaaS#141]
Hi,

In module:
https://github.com/CheckPointSW/CloudGuardIaaS/blob/master/terraform/aws/management

Problem adding multiple Admin CIDR not allowed in for management module.

Expected: 
Add an array of CIDR's to admin_cidr

Current:
Only one CIDR allowed so if have more enabling insecure 0.0.0.0/0 , this would mean to secure would need to limit this and then afterwards additionally add other CIDR

In file https://github.com/CheckPointSW/CloudGuardIaaS/blob/master/terraform/aws/management/main.tf
It allows for a block of CIDR
` cidr_blocks = [var.admin_cidr]`
but the variable is only allowed to be once CIDR.
File: https://github.com/CheckPointSW/CloudGuardIaaS/blob/master/terraform/aws/management/variables.tf
`variable "admin_cidr" {
  type = string
  description = "(CIDR) Allow web, ssh, and graphical clients only from this network to communicate with the Security Management Server"
  default = "0.0.0.0/0"
}`

If you have multiple Office CIDR you want to connect you have to add them after wards.
Can this be change to a list(string) instead of a string.

Feel free to ping me at Yaakov Goodman in Checkpoint

**Comment by chkp-romanka** [comment]
Hi @ygoodmn 
We  are checking it and will update

**Comment by chkp-romanka** [comment]
The feature request added to roadmap 2023
