### ISSUE TITLE
Noinbound port rule to access firewall from external IP. 

### ISSUE THREAD

**Issue by rajeev-cloud** [CheckPointSW/CloudGuardIaaS#148]
Hi, 

thank you for fixing the earlier issue, today i was testing the code and found inbound port rule is still missing and because of that i am unable to access firewall external IP from internet. I had to manually create a NSG for inbound port rule to get firewall access and similar problem for outbound port rule. 

![an](https://user-images.githubusercontent.com/83108927/145334496-274dd895-02d4-4618-b8b3-dec15d549b9b.JPG)

**Comment by chkp-arielto** [comment]
Hi @rajeev-cloud 
After investigation, we are indeed configuring these security groups.
Can you please ensure that you use the latest Azure HA terraform template in this repository?
Thanks,
Ariel

**Comment by rajeev-cloud** [comment]
Yes, I am using latest Azure HA template and after investigation I found missing NSG.

**Comment by chkp-arielto** [comment]
I suggest doing a remote session.
Please contact me offline (arielto@checkpoint.com), then we can go over this together.

**Comment by rajeev-cloud** [comment]
Thank you for your time for discussion, 

Here is the solution for firewall external IP access - 

resource "azurerm_network_security_group" "nsg" {
  
  name = var.network_sg_name
  location = var.location
  resource_group_name = data.azurerm_resource_group.rg.name

security_rule = [ 

//Place all Inbound rule here
  {access = "Allow",  description = "AllowInBound" , destination_address_prefix = "*", destination_address_prefixes = null
  destination_application_security_group_ids = null, destination_port_range = "*", destination_port_ranges = null
  direction = "Inbound", name = "AllowAllInbound",  priority = 100,  protocol = "*",  source_address_prefix = "*"
  source_address_prefixes = null,  source_application_security_group_ids = null,  source_port_range = "*",  
  source_port_ranges = null},

//Place all Outbound rule here
  {access = "Allow",  description = "AllowInBound" , destination_address_prefix = "*", destination_address_prefixes = null
  destination_application_security_group_ids = null, destination_port_range = "*", destination_port_ranges = null
  direction = "Outbound", name = "AllowAllOutbound",  priority = 100,  protocol = "*",  source_address_prefix = "*"
  source_address_prefixes = null,  source_application_security_group_ids = null,  source_port_range = "*",  
  source_port_ranges = null},
 
   ]

**Comment by chkp-arielto** [comment]
Hi @rajeev-cloud 
After further investigation, the existing VNET was not deployed either with inbound rule or with NSGs on the GW NICs.
When customers deploy using an existing VNET, they are responsible for the NSGs and UDRs.
Thanks,
Ariel
