### ISSUE TITLE
Update Admin Guide Link in terraform\gcp\high-availability\README.md

### ISSUE THREAD

**Issue by chkp-bryans** [CheckPointSW/CloudGuardIaaS#168]
Update Admin Guide Link in terraform\gcp\high-availability\README.md 

"See Check Point's documentation for Cluster High Availability (HA) **[here]**"

**Correct Link -** https://sc1.checkpoint.com/documents/IaaS/WebAdminGuides/EN/CP_CloudGuard_IaaS_HighAvailabilty_for_GCP/Content/Topics-GCP-HA/CP-CloudGuard-IaaS-HA-for-GCP.htm 

Current Link - (https://sc1.checkpoint.com/documents/IaaS/WebAdminGuides/EN/CP_CloudGuard_IaaS_HighAvailabilty_for_GCP/Content/Topics/Check_Point_CloudGuard_IaaS_High_Availability_for_GCP.htm?tocpath=Check%20Point%20CloudGuard%20IaaS%20High%20Availability%20for%20GCP%7C_____0)

**Comment by chkp-dmitrygo** [comment]
Done, thank you for bringing this to our attention
