### ISSUE TITLE
ClusterXL error when deploy HA configuration to Azure

### ISSUE THREAD

**Issue by Xyders** [CheckPointSW/CloudGuardIaaS#179]
Hi, anyone can give me some advice about this.
I cannot solve the error of ClusterXL: "Member state: ClusterXL inactive or machine is down", after I created the cluster from SmartConsole.
Detailed info in Problem Notification Table was like, Fullsync: problem, routed: problem, others are OK.
I can ssh to my cluster members. Don't know if this is the problem, but I found that I can only see ipconfig1 of nic_vip(10.0.1.5), cannot even ping the other ip-configuration(10.0.1.7).

**Comment by chkp-natanelm** [comment]
Hi @Xyders,
Please refer to  [sk175023](https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk175023).

If you still encounter issues, please contact your local Check Point Support and attach the following files to the case to speed-up the process:
- /etc/cloud-version
- $FWDIR/conf/azure-ha.json
- $FWDIR/log/azure_had.elg*
- /var/log/cloud_config.log
- $FWDIR/boot/modules/fwkern.conf
- curl_cli --verbose https://management.azure.com --cacert $FWDIR/conf/ca-bundle-public-cloud.crt > /home/admin/azure-connectivity.txt
- $FWDIR/scripts/azure_ha_test.py > /home/admin/ha-tester-output.txt
- cphaprob state > /home/admin/cphaprob-stat.txt

Thanks,
Natanel
