### ISSUE TITLE
should we update the file management_user_data.sh? in the folder 'terraform/aws/management/'

### ISSUE THREAD

**Issue by Xyders** [CheckPointSW/CloudGuardIaaS#186]
currently version of this file has following lines:
```
chkconfig --add autoprovision
service autoprovision start
```
But this caused problem in my environment, I found this error in log file /var/log/aws-user-data.log 
```
Running service autoprovision start...
error reading information on service autoprovision: No such file or directory
```
The workaround worked for me was just remove these 2 lines, cos I think the CME was already installed successfully and the service is running properly. But I'm not sure this is recommended officially so I would like to ask your help to confirm and update this file accordingly.

**Comment by chkp-romanka** [comment]
Hi @Xyders 
Thanks for notifying 
We understand the issue and will deliver fix shortly

**Comment by chkp-romanka** [comment]
@Xyders 
The fix delivered
Thanks
