### ISSUE TITLE
Option to manage Azure VMSS instance on public IP

### ISSUE THREAD

**Issue by geertdr** [CheckPointSW/CloudGuardIaaS#25]
Azure VMSS Terraform template should preferably have an option to manage the instances on their public IP.

x-chkp-ip-address = "public"

**Comment by chkp-romanka** [comment]
Hello Geert,
Currently this is limitation
It will be removed when we advance to the latest Azure provider which was released a few days ago. Keep watching the revision history to be updated.

**Comment by amit-schnitzer** [comment]
+1 on the public IP stuff... 
In the meantime, I have created a fork which automatically create peering between the management vNET and the new VMSS vNET (currently only on vmss-new-vnet)

**Comment by chkp-dmitrygo** [comment]
Instance level IP support for VMSS is considered for a future release. Regarding the fork - this is great news and great initiative. Feel free to create a pull request to the "contrib" directory with that template if you wish.
Thanks
