### ISSUE TITLE
Terraform aws instance type comma error

### ISSUE THREAD

**Issue by cadgo** [CheckPointSW/CloudGuardIaaS#268]
Line 103 needs to have a "," comma separator on the list, this is the master branch and is dropping the error 

 Error: Missing item separator
│
│ On ../modules/common/instance_type/main.tf line 104: Expected a comma to mark the beginning of the next item.

**Comment by chkp-romanka** [comment]
@cadgo 
Thanks for notifying 
The issue resolved
