### ISSUE TITLE
azure_ha_test.py does not work after upgrade to R81.10

### ISSUE THREAD

**Issue by rgilijamse** [CheckPointSW/CloudGuardIaaS#273]
The Azure HA test script (azure/misc/azure_ha_test.py) no longer works after in-place upgrade to R81.10 (following sk177714).

```
[Expert@hostname:0]# /opt/CPsuite-R81.10/fw1/scripts/azure_ha_test.py
Image version is: azure_blink_image_Check_Point_ignis_main_T335_135854
Error:
list index out of range
```

This is because the code to extract `branch` and `take_number` variables from `image_version` does not work with this image name:
https://github.com/CheckPointSW/CloudGuardIaaS/blob/797ad660fbc1b65f1df62d81d1d3427a0f3938cd/azure/misc/azure_ha_test.py#L232

Hardcoding `branch` and `take_number` in the script allows the script to run, but this is not a scalable solution.

**Comment by chkp-natanelm** [comment]
Hi @rgilijamse,

Thank you for your comment. 
The[ azure_ha_test.py](https://github.com/CheckPointSW/CloudGuardIaaS/blob/797ad660fbc1b65f1df62d81d1d3427a0f3938cd/azure/misc/azure_ha_test.py) script is not up to date with the one that the machine should have.

We changed this code to support IPU a long time ago.
Could you please share your package take and build (/etc/cloud-version)?

Thanks,
Natanel

**Comment by chkp-natanelm** [comment]
Thank you @rgilijamse.
According to your output, this is indeed an old version package, we are working to release a new IPU package to include the fix.
In the meanwhile, we updated the [azure_ha_test.py](https://github.com/CheckPointSW/CloudGuardIaaS/blob/master/azure/misc/azure_ha_test.py) script, please replace it with your tester and test again.

Thanks,
Natanel
