### ISSUE TITLE
Terraform Code to deploy mds in Azure

### ISSUE THREAD

**Issue by JihedTounsiTR** [CheckPointSW/CloudGuardIaaS#276]
Hello Checkpoint,

Is there a plan to have terraform code to deploy MDS in Azure? Or can you please suggest tweaks to existing code?

I have tried to set some variables in the `terraform`[`management deployment`](https://github.com/CheckPointSW/CloudGuardIaaS/tree/master/terraform/azure/management-existing-vnet) with values that I can see in the [`ARM templates`](https://github.com/CheckPointSW/CloudGuardIaaS/tree/master/azure/templates/marketplace-mds) in this repo. For example:

```
variable "installation_type" {
  description = "Installation type"
  type        = string
  default     = "mds-primary" 
}
```
I also added it to the `variables.tf` of the `common` module:
```
locals { // locals for 'installation_type' allowed values
  installation_type_allowed_values = [
    "cluster",
    "vmss",
    "management",
    "mds-primary"
  ]
  // will fail if [var.installation_type] is invalid:
  validate_installation_type_value = index(local.installation_type_allowed_values, var.installation_type)
}
```
And also update the version
```
variable "template_version" {
  description = "Template version. It is recommended to always use the latest template version"
  type        = string
  default     = "20230124"
}
```

But of course it did not work 😅, I think I am missing more than just those variables. It was worth a try before opening this issue.

```
[Expert@cp-mds-vpndmz:0]# mdsconfig
bash: mdsconfig: command not found
```

```
[Expert@cp-mds-vpndmz:0]# mdsstart_start 
/bin/mdsstart_start: line 11: /scripts/mdsstart: No such file or directory
```

Please let me know if I should open a support ticket instead.

Many thanks.

**Comment by chkp-natanelm** [comment]
Hi @JihedTounsiTR,

Thank you for your feedback.
We are currently working to release more Terraform solutions for Azure.
The release should be done during July.

In the meanwhile, you can use the GA-grade Terraform templates at https://github.com/CheckPointSW/CloudGuardIaaS/tree/yairra-azure-terraform-alignments/terraform/azure (including MDS).

Thanks,
Natanel

**Comment by JihedTounsiTR** [comment]
Hi Natanel,

Thank you for your response. I look forward  to more Terraform from the team. I will definitely test out the code from the link you shared.

Kind regards,
Jihed
