### ISSUE TITLE
SIC not configured on deployment  

### ISSUE THREAD

**Issue by simonmacpherson** [CheckPointSW/CloudGuardIaaS#282]
This is in reference to deploying Check Point CloudGuard IaaS High Availability solution into an existing Vnet in Azure using the following repository:

https://github.com/CheckPointSW/CloudGuardIaaS/tree/master/terraform/azure/high-availability-existing-vnet

It does not appear terraform/azure/high-availability-existing-vnet/cloud-init.sh that runs python3 /etc/cloud_config.py to configure SIC during boot is working. 

I am unable to establish SIC with each the gateway post-deployment. I need to manually reset SIC on each gateway before I can establish SIC.

**Comment by chkp-yairra** [comment]
Hi Simon,
I've tested this scenario and managed to deploy an HA into an existing Vnet and configure SIC after deployment (without resetting the SIC password on the gateways).
you're welcome to contact me (yairra@checkpoint.com) and deploy your environment together if needed.

**Comment by simonmacpherson** [comment]
Hi @chkp-yairra the problem was deploying from a windows machine running Terraform v1.5.2. The cloud-init.sh doesn't seems to run correctly when run from Windows. The script runs successfully when deploying from RHEL Linux running Terraform v1.5.3.  Initially I could replicate the issue on this server. After running yum update -y, the cloud-init.sh script started to run as expected.  So I'm not sure exactly what was causing it to initially not run correctly.
