### ISSUE TITLE
VMSS depracated resource

### ISSUE THREAD

**Issue by amaol** [CheckPointSW/CloudGuardIaaS#297]
Hi,

Can you please update the VMSS definition for the latest updates regarding the resource definition in terraform, just receive this log during terraform run:

Warning: Deprecated Resource
│ 
│   with module.vmss.azurerm_virtual_machine_scale_set.vmss,
│   on .terraform/modules/vmss/modules/vmss-cldgd/main.tf line 300, in resource "azurerm_virtual_machine_scale_set" "vmss":
│  300: resource "azurerm_virtual_machine_scale_set" "vmss" {
│ 
│ The 'azurerm_virtual_machine_scale_set' resource has been superseded by the
│ 'azurerm_linux_virtual_machine_scale_set' and
│ 'azurerm_windows_virtual_machine_scale_set' resources. Whilst this resource
│ will continue to be available in the 2.x and 3.x releases it is
│ feature-frozen for compatibility purposes, will no longer receive any
│ updates and will be removed in a future major release of the Azure
│ Provider.

Thanks in advance,

António Oliveira

**Comment by chkp-yairra** [comment]
HI @amaol,
This update is part of our backlog and we will update it ASAP,
Meanwhile, if you need any help deploying it by yourself feel free to contact me - yairra@checkpoint.com
Thanks!
