### ISSUE TITLE
Azure Virtual Machine Scale Set Plan Block required with custom images. 

### ISSUE THREAD

**Issue by RyanMarkoff-eaton** [CheckPointSW/CloudGuardIaaS#320]
On Azure Virtual Machines and Virtual Machine Scale Sets a `plan` block is required when using an existing image like from checkpoint. 

Here is the provider documentation:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine_scale_set#plan

When the plan block is not supplied with the image Azure will report the error 

> Creating a virtual machine from Marketplace image requires Plan information in the request.

Once the plan block was supplied like this the virtual machines deployed correctly.
```
plan {
    name      = "sg-byol"
    publisher = "checkpoint"
    product   = "check-point-cg-r8110"
  }
```
I used the the existing `vmss-existing-vnet` template and had several failed deployments until adding the plan block with those values. The `name` seems to be the license name which isn't exactly intuitive, and I think it should be made more clear in the documentation going forward. Thanks.

**Comment by chkp-natanelm** [comment]
We appreciate your feedback @RyanMarkoff-eaton regarding this problem.
Our team will look into it and fix our TF deployment as soon as possible.

**Comment by chkp-natanelm** [comment]
@RyanMarkoff-eaton could you please share your "source_image_vhd_uri" field in terraform.tfvars file?

**Comment by RyanMarkoff-eaton** [comment]
@chkp-natanelm I'm using `noCustomUri`

**Comment by chkp-natanelm** [comment]
@RyanMarkoff-eaton,

We do mention the plan block as part of our TF template. 
https://github.com/CheckPointSW/CloudGuardIaaS/blob/master/terraform/azure/vmss-new-vnet/main.tf#L267

We were unable to replicate this issue on our end.
Please contact Check Point's support and create a ticket, so we can provide you with optimal assistance.
https://www.checkpoint.com/support-services/contact-support/

**Comment by RyanMarkoff-eaton** [comment]
@chkp-natanelm Correct, but nothing in the readme mentions it and when I to updated the the out of date azure provider used in the codebase it would have been much easier to resolve with documentation. I have already engaged checkpoint support and was advised to submit this issue.

**Comment by chkp-natanelm** [comment]
@chkp-natanelm we advise against making any modifications to the Azure provider of our deployments, as this may lead to some unforeseen problems.
Could you please provide the SR number so I can review it internally?

**Comment by chkp-natanelm** [comment]
We apologize for the inconvenience caused by the above issue. 
Our team is working hard to resolve it as soon as possible. However, the process is complex and we cannot give you an exact time frame for completion.
