### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by veldpworld** [CheckPointSW/CloudGuardIaaS#324]
I have requirement to create checkpoint firewall and vpn along with azure route server.

I seen 4 different module and not sure which one is for what ?  Can you add more details on the readme

**Comment by chkp-natanelm** [comment]
Hi @veldpworld,

You have two options for VPN termination when deploying the check point firewall in Azure: Single Gateway or High Availability Cluster.

For the Check Point firewall deployment in Azure you have 2 deployment types for VPN termination: Single Gateway or High Availability Cluster.

You can choose one of the following methods for each option:
1. Deploy from the Azure marketplace
2. Custom ARM template deployment (see https://github.com/CheckPointSW/CloudGuardIaaS/tree/master/azure/templates for details) 
3. Terraform deployment (see https://github.com/CheckPointSW/CloudGuardIaaS/tree/master/terraform/azure for details) 

If you have any further questions, please reach out to Check Point's support and open a ticket. We will be happy to assist you.
https://www.checkpoint.com/support-services/contact-support/

Thanks,
Natanel
