### ISSUE TITLE
Please remove all providers in modules

### ISSUE THREAD

**Issue by Xyders** [CheckPointSW/CloudGuardIaaS#328]
Hi

From guide of Terraform, there should be no providers in modules, but there're many such things in the code that cause errors, can you remove them? 

https://developer.hashicorp.com/terraform/language/modules/develop/providers

"Provider configurations can be defined only in a root Terraform module."

"A module intended to be called by one or more other modules must not contain any provider blocks."

Scott

**Comment by chkp-romanka** [comment]
Hi @Xyders 
Appreciate your feedback 
We evaluating removing provider block from part of our modules
Meanwhile you can put provider block in comments as it is explained in README.md of our solutions templates 
For example from Management template:
 https://github.com/CheckPointSW/CloudGuardIaaS/tree/master/terraform/aws/gateway#configurations
