### ISSUE TITLE
Azure HA terraform issue with NICs creation

### ISSUE THREAD

**Issue by templier2** [CheckPointSW/CloudGuardIaaS#332]
Hello.
When I am running "high-availability-new-vnet", each time terraform loops at creating two nics and network association (two other nics are created).
If I stop and retry running, it will continue deploying successfully.
AzureRM 2.92, Terraform 1.66.
UPD:
Terraform destroy also loops.

**Comment by templier2** [comment]
I would suggest changing versions.tf to
version = "~> 2.92"
It allows upgrading to 2.99 and fixes problems with NICs creation.

**Comment by chkp-yairra** [comment]
Hi @templier2,
Thanks for the update,
We are working on updating the azurerm provider version in the Azure HA Terraform templates and it will be available soon.

Thanks,
Yair
