### ISSUE TITLE
Password problem

### ISSUE THREAD

**Issue by raylauhk** [CheckPointSW/CloudGuardIaaS#347]
when finished the terraform execution, the gateway_password_hash seems cannot apply correctly and cannot login with the defined password

**Comment by chkp-dmitrygo** [comment]
which solution are you trying to deploy?

**Comment by raylauhk** [comment]
cloudguard network security on alicloud platform

**Comment by chkp-dmitrygo** [comment]
which specific solution from https://github.com/CheckPointSW/CloudGuardIaaS/tree/master/terraform/alicloud?

**Comment by raylauhk** [comment]
used the below solution 
1. management <no problem with the password hash entered.>
2. cluster <got the password hash problem even use the same value from the management.>
3. run the cli  "openssl passwd -6 PASSWORD" to generate the hash 
4. copy to the variables password_hash and gateway_password_hash 

Result - management can login but the gateway couldn't. Suppose use "admin" to logon the GAiA WebUI and got the Permission denied

**Comment by raylauhk** [comment]
Do you got the same problem? both gateway and cluster cannot login with the defined password...

**Comment by raylauhk** [comment]
Hi, May I have the update? we are in the pre-deployment stage and reported this to our local SE team of Check Point too. Hope can line up for further support, thank you.

**Comment by almogard** [comment]
Hi @raylauhk ,
I'm investigating that, for now please use the private key pair for authentication.

**Comment by raylauhk** [comment]
The result was, we have to reset the password by using the private key to login the clish. wondering the password policy affecting it...

**Comment by almogard** [comment]
for now if you deploy new instance restart the password by that command:
_set user admin password-hash "PASSWORD"
save config_

**Comment by chkp-natanelm** [comment]
We are closing this ticket for now as it appears the issue has been resolved. 
Should you encounter any further problems or if the issue persists, please do not hesitate to reopen this issue or contact Check Point's support.
