### ISSUE TITLE
Depreacated ressources used

### ISSUE THREAD

**Issue by edacostaa** [CheckPointSW/CloudGuardIaaS#356]
│ Warning: Argument is deprecated
│
│   with azurerm_lb_backend_address_pool.frontend-lb-pool,
│   on main.tf line 111, in resource "azurerm_lb_backend_address_pool" "frontend-lb-pool":
│  111:  resource_group_name = module.common.resource_group_name
│
│ This field is no longer used and will be removed in the next major version of the Azure Provider
│
│ (and 12 more similar warnings elsewhere)
╵
╷
│ Warning: Deprecated attribute
│
│   on ../modules/vnet/main.tf line 48, in resource "azurerm_route_table" "frontend":
│   48:     address_prefix = azurerm_subnet.subnet[0].address_prefix
│
│ The attribute "address_prefix" is deprecated. Refer to the provider documentation for details.
│
│ (and 3 more similar warnings elsewhere)

**Comment by chkp-natanelm** [comment]
Hi @edacostaa,
Thank you for reaching out and for your patience. We wanted to confirm that we are on track with the development of the new version, addressing the deprecation issues. 
Our team is working to ensuring a smooth transition and we anticipate having the update ready by the end of the month.

We appreciate your understanding and support.
For any further questions or require assistance do not hesitate to contact us again. 

Thanks
