### ISSUE TITLE
error when using the "terraform validate"! 

### ISSUE THREAD

**Issue by raylauhk** [CheckPointSW/CloudGuardIaaS#367]
what is the problem when I used the "terraform validate" ? 

 terraform validate
╷
│ Error: Module module.gwlb.module.autoscale_gwlb contains provider configuration
│ 
│ Providers cannot be configured within modules using count, for_each or depends_on.
╵
╷
│ Error: Module module.gwlb.module.management.module.cme_iam_role contains provider configuration
│ 
│ Providers cannot be configured within modules using count, for_each or depends_on.
╵
╷
│ Error: Module module.gwlb.module.management.module.cme_iam_role_gwlb contains provider configuration
│ 
│ Providers cannot be configured within modules using count, for_each or depends_on.
╵
╷
│ Error: Module module.gwlb.module.management contains provider configuration
│ 
│ Providers cannot be configured within modules using count, for_each or depends_on.
╵
╷
│ Error: Cannot override provider configuration
│ 
│   on main.tf line 229, in module "gwlb":
│  229:     aws = aws
│ 
│ Provider aws is configured within the module module.gwlb and cannot be overridden.
╵
╷
│ Error: Cannot override provider configuration
│ 
│   on ../gwlb/main.tf line 39, in module "autoscale_gwlb":
│   39:     aws = aws
│ 
│ Provider aws is configured within the module module.gwlb.module.autoscale_gwlb and cannot be overridden.
╵
╷
│ Error: Cannot override provider configuration
│ 
│   on ../gwlb/main.tf line 72, in module "management":
│   72:     aws = aws
│ 
│ Provider aws is configured within the module module.gwlb.module.management and cannot be overridden.
╵
╷
│ Error: Cannot override provider configuration
│ 
│   on ../management/main.tf line 178, in module "cme_iam_role":
│  178:     aws = aws
│ 
│ Provider aws is configured within the module module.gwlb.module.management.module.cme_iam_role and cannot be overridden.
╵
╷
│ Error: Cannot override provider configuration
│ 
│   on ../management/main.tf line 189, in module "cme_iam_role_gwlb":
│  189:     aws = aws
│ 
│ Provider aws is configured within the module module.gwlb.module.management.module.cme_iam_role_gwlb and cannot be overridden.

**Comment by chkp-romanka** [comment]
Hello @raylauhk 
As written in the readme.md for GWLB solution it is required to comment provider block for several modules
_In case the Static credentials are used, perform modifications described below:
a. The next lines in main.tf file, in the provider aws resource, need to be commented for sub-modules /terraform/aws/autoscale-gwlb, /terraform/aws/management and /terraform/aws/cme-iam-role-gwlb:
provider "aws" {
//  region = var.region
//  access_key = var.access_key
//  secret_key = var.secret_key
}_
After commenting provider modules, deployment should work
Let me know if you still have any deployment issues
Thanks
