### ISSUE TITLE
Use IP-prefixlist in Azure terraform vmss existing vnet code

### ISSUE THREAD

**Issue by TBWW** [CheckPointSW/CloudGuardIaaS#393]
In the azure portal it is possible to use a ip-prefix list for the virtaul scaleset. (vmss)
In this repository this possibility is only available für ha-gateways.
is it planned to support the usage of ip-prefixlists for vmss in the azure terraform code?

**Comment by chkp-natanelm** [comment]
Hi @TBWW,
The requested feature is on our development backlog, but we're unable to provide a specific timeline for its release at this time.
Thanks
