### ISSUE TITLE
azure CloudGaurdIaaS to Bicep

### ISSUE THREAD

**Issue by darrenFrowen** [CheckPointSW/CloudGuardIaaS#394]
Hi,

As most organisations are starting to moving away from developing with ARM JSON to Azure Bicep domain specific language is there any road map to convert these templates? I have tried to de-compile into Bicep using VSC but this fails with multiple issues. Microsoft has now released Azure Verified Modules https://github.com/Azure/bicep-registry-modules which could also be of benefit.

Thanks in advance

**Comment by chkp-natanelm** [comment]
Hi @darrenFrowen, 

Bicep is indeed part of our project backlog. However, due to the dynamic nature of our priorities and resources, I'm unable to provide a definitive timeline for this project.

Thanks

**Comment by darrenFrowen** [comment]
Hi @chkp-natanelm,

Thanks for the update and understood.
