### ISSUE TITLE
[terraform/gcp/single-into-existing-vpc] - Issue with DiskType Variable and Validation

### ISSUE THREAD

**Issue by timbohiatt** [CheckPointSW/CloudGuardIaaS#399]
Hey All, 

In the terraform script for deploying to GCP with a Single Instance to an Existing VPC; 

You provide a Default variable of "pd-ssd" in the variables.tf

```
variable "diskType" {
  type = string
  description ="Disk type"
  default = "pd-ssd"
}
```
however in locals.tf you run several validations; 
The issue is the validation of if variable ```diskType``` is conducted on line 40

```
validate_disk_type = index(local.disk_type_allowed_values, var.diskType)
```

comparing local variable ```var.diskType``` (defaulted to ```pd-ssd``` against a list ```disk_type_allowed_values``` which is defined as: 

```
  disk_type_allowed_values = [
    "SSD Persistent Disk",
    "Balanced Persistent Disk",
    "Standard Persistent Disk"]
``` 

Therefore when using your default variable; The terraform plan fails as the default value of ```pd-ssd``` is not in the list of allowed variables. 

It is an assumption; However I believe the Array of ```disk_type_allowed_values``` has been defined incorrectly and that rather it should be defined as: 

```
  disk_type_allowed_values = [
    "pd-ssd",
    "pd-balanced",
    "pd-standard"]
``` 

Please note; Incase this assumption is correct I will raise a PR with the suggested modification for your review. 
Thanks.

**Comment by timbohiatt** [comment]
Linked to PR:
#https://github.com/CheckPointSW/CloudGuardIaaS/pull/400

**Comment by chkp-yairra** [comment]
Hi @timbohiatt 

Thank you for your feedback!
We've fixed this issue by updating the default value,
The disk type of the machine is determined according to the diskType parameter:(https://github.com/CheckPointSW/CloudGuardIaaS/blob/ed802d8053782da35474af192aaba468ff3f65b0/terraform/gcp/single-into-existing-vpc/locals.tf#L42C3-L42C47)

Thanks again for your feedback and the suggestion, it is much appreciated
Yair
