### ISSUE TITLE
The management template _artifactsLocation caused a failure

### ISSUE THREAD

**Issue by Don-Paterson** [CheckPointSW/CloudGuardIaaS#410]
When I ran New-AzResourceGroupDeployment -ResourceGroupName $resourceGroupName -TemplateFile $templateFilePath -TemplateParameterFile $parametersFilePath it failed because of the _artifactsLocation 

template.json
parameters.json <-- downloaded from Marketplace, at end of management 

Fixed with this:
"_artifactsLocation": {
    "type": "string",
    "metadata": {
        "description": "Use the following URI when deploying a custom template: https://raw.githubusercontent.com/CheckPointSW/CloudGuardIaaS/master/azure/templates/"
    },
    "defaultValue": "https://raw.githubusercontent.com/CheckPointSW/CloudGuardIaaS/master/azure/templates/"
}

I also found this issue with the marketplace-vmss template, where I had to put the url into two lines before the verify and New-AzResourceGroupDeployment would succeed.

**Comment by chkp-natanelm** [comment]
Hi @Don-Paterson, 

The “_artifactsLocation” parameter is used exclusively for custom deployments. The marketplace templates differ in that they do not utilize the “_artifactsLocation” parameter, as the nested templates are included within the marketplace files necessary for deploying the solutions.

Please let me know if this addresses your concerns so I can proceed with closing this issue.

Thanks, 
Natanel

**Comment by Don-Paterson** [comment]
Thanks @chkp-natanelm 

I understand now.
Please do go ahead and close the issue. 

Regards,
Don
