### ISSUE TITLE
Unable to login to GAiA portal

### ISSUE THREAD

**Issue by satyamsinha1991** [CheckPointSW/CloudGuardIaaS#412]
I am trying to connect to connect the checkpoint-management server (https://ip-of-management-server) from the checkpoint web server, what is the username and password I have to use to login to GAiA portal? I am using the terraform script as provided in the repo to create 

- https://github.com/CheckPointSW/CloudGuardIaaS/tree/master/terraform/azure/management-existing-vnet
- https://github.com/CheckPointSW/CloudGuardIaaS/tree/master/terraform/azure/single-gateway-existing-vnet

**Comment by chkp-natanelm** [comment]
Hi @satyamsinha1991,
The default username is “admin”.
For the password, it depends on the "authentication_type" parameter you selected:
- Password: Use this to log in to the GAIA portal.
- SSH Public Key: Need to manually set the admin password (can use command "set user admin password" in expert mode).

Hope it answers your question.
Thanks

**Comment by satyamsinha1991** [comment]
Hello @chkp-natanelm ,
Thankyou for your response
I had authentication_type as false and I was able to login using admin and Password from my checkpoint web server. 
When I tried again surprisingly  admin and Password doesn't work now. Do I need to change the password ?

**Comment by chkp-natanelm** [comment]
Hi @satyamsinha1991,

The value “False” is not valid for the “authentication_type” parameter, which should be set to either “Password” or “SSH Public Key”. If an incorrect value is pushed, the deployment should fail with a warning.
![image](https://github.com/user-attachments/assets/1c0854fc-c9a1-46ee-ab65-05a87326c562)

Additionally, the Gaia portal functions the same for CloudGuard Network Security Gateways and Management. 
For troubleshooting Gaia portal login issues, please refer to the following link: [Gaia Portal Troubleshooting](https://sc1.checkpoint.com/documents/R81.10/WebAdminGuides/EN/CP_R81.10_Gaia_AdminGuide/Topics-GAG/Advanced-Gaia-Configuration.htm).

If you still need assistance with this issue, please contact [Check Point support](https://www.checkpoint.com/support-services/contact-support/).
Thanks
