### ISSUE TITLE
Azure Version

### ISSUE THREAD

**Issue by hschol** [CheckPointSW/CloudGuardIaaS#450]
In versions.tf (https://github.com/CheckPointSW/CloudGuardIaaS/blob/master/terraform/azure/vmss-existing-vnet/versions.tf)
terraform {
  required_version = ">= 0.14.3"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.90.0"
    }
    random = {
      version = "~> 3.5.1"
    }
  }
}

Our platform demands 4.5.0 for hashicorp/azurerm is it possible to make 4.5.0 work for us

**Comment by chkp-natanelm** [comment]
Hi @hschol, 
Thank you for your request regarding the upgrade to version 4.5.0 of the hashicorp/azurerm provider.

We have reviewed your request, and implementing this change will require significant effort and careful planning, with a high level of risk. 
While we are continuously working to maintain and improve our solutions, and this upgrade is part of our long-term plan, the complexity involved means it would be best to reach out to the Check Point support system to submit a Request for Enhancement (RFE) to expedite the process.

For now, I will close this issue. Please let us know if you have any further questions or need additional assistance.

Thanks,
Natanel
