### ISSUE TITLE
vmss-existing-vnet doesn't create an nsg

### ISSUE THREAD

**Issue by geertdr** [CheckPointSW/CloudGuardIaaS#51]
vmss-new-vnet creates a nsg on eth0 of the scale set.
vmss-existing-vnet doesn't do that however a nsg is required on the subnet or nic by the standard public load balancer in order to allow traffic to the scale set.

Any reason for this? It took me a while to investigate what was wrong so I would either:
- add nsg creation to vmss-new-vnet
- document the requirement for an nsg in README

**Comment by chkp-dmitrygo** [comment]
Hi,
This is by design and similar to the marketplace deployment and documented in the VMSS admin guide.
When you deploy to an existing VNET, we do not modify any VNET configurations including NSGs, that is in order to prevent surprises.

Thanks,
Dmitry
