### ISSUE TITLE
GCP: make private static routes defined in the boot script configurable

### ISSUE THREAD

**Issue by bastiaanb** [CheckPointSW/CloudGuardIaaS#57]
The boot script of the VM in the GCP deployment manager template creates a hardcode list of static routes to RFC1918 subnets on the internal network.
This is undesirable for deployments with multiple internal interfaces.
Proposal: add a variable 'privateStaticRoutes' with a space separate list of subnets to configure at boot time. Each subnet may optionally be suffixed with `:<interface-number>` to specify an alternative interface (than `internalInterfaceNumber`).
E.g. 
```
privateStaticRoutes: 10.0.0.0/8 10.1.0.0/16:2 10.2.0.0/16:3
``` 
Please let me know if this is an acceptable proposal, then I'll create a PR for it.

**Comment by chkp-arielto** [comment]
Hi Bastian, 
Thanks for reaching out!

The concern that you mentioned is real, however, most of our users deploy CloudGuard solutions with only one internal interface, and then, the default configuration suits them.

I would like to suggest another generic solution for solving it:
As the solution proposed can be difficult to configure for users (the input may not be in the expected format, the subnets may be wrong, the interfaces may not exist..), I would suggest implementing a variable that gets a bootstrap script as argument.
Then the inputted script is run from the VM.

Hence, we can configure the static routes using this script (RFC-1918 addresses will always be configured through the first internal interfaces, but specific routes that will take priority can be configured using bootsrapt script).
Besides, the script can be used for other matters in the future.

Please let me know what do you think about it.

Thanks,
Ariel
