### ISSUE TITLE
Azure terraform template using deprecated ressource

### ISSUE THREAD

**Issue by edacostaa** [CheckPointSW/CloudGuardIaaS#67]
Warning: "network_security_group_id": [DEPRECATED] Use the `azurerm_subnet_network_security_group_association` resource instead.

**Comment by chkp-arielto** [comment]
Thanks for letting us know.
We'll go over the Azure Terraform templates in the upcoming week, and check this resource if needed

**Comment by chkp-arielto** [comment]
Hi @edacostaa 
We've modified our terraform templates to use `azurerm_subnet_network_security_group_association` resource.
We'll publish the change in the next 2 weeks.
Thanks for the support.
Ariel
