### ISSUE TITLE
Is it supported to deploy CloudGuard HA manually

### ISSUE THREAD

**Issue by StefanIvemo** [CheckPointSW/CloudGuardIaaS#73]
I've changed the marketplace-ha template to add a Public IP Prefix, I don't want randomly assigned Public IP Addresses. I've also updated resource names to match my customers naming standard and also make sure that the naming is a bit more descriptive. If I deploy the template manually is there something that can go wrong that would affect support, licensing or other? 

I'm a bit confused by the first declared resource in the template, an empty nested deploy. Is the deployment ID something that's used during support requests or something like that?

```json
    {
      "apiVersion": "2020-06-01",
      "name": "pid-7fbd7ca2-a62c-5cb5-9b28-3900ca6dba8d",
      "type": "Microsoft.Resources/deployments",
      "properties": {
        "mode": "Incremental",
        "template": {
          "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
          "contentVersion": "1.0.0.0",
          "resources": []
        }
      }
    }
```

**Comment by chkp-arielto** [comment]
Hi Stefan,

Thank you for your contribution.

We will review and test the modification, and consider integrating it into our official marketplace templates.
Meanwhile, please change the pull request to use the contrib/azure/template/ha-public-ip-prefix directory.

Check Point doesn't support customize template deployments.
Therefore, we suggest confirming a customize template in advance with support or with Check Point local office.

The PID resource is mandatory for publication in Azure marketplace.
This correlates the template deployment to Azure marketplace offering and should be kept as is.

Please let me know if additional information is required.

Thanks,
Ariel

**Comment by StefanIvemo** [comment]
@chkp-arielto if I want to confirm my custom template with support, what support channel should I use for that? The deployment is succeeding and the cluster is working. 

I will remove the Pull Request and create a new one and move the template to the correct folder.

**Comment by chkp-dmitrygo** [comment]
Hello @StefanIvemo,
Please open a support ticket ("SR") at https://www.checkpoint.com/support-services/contact-support/ or contact the Check Point Local Office in your area at https://www.checkpoint.com/about-us/contact-us/

Thank you for your contribution and for updating the pull request.

**Comment by StefanIvemo** [comment]
Thank you for the information!
