### ISSUE TITLE
AWS terraform ami module using deprecated repository

### ISSUE THREAD

**Issue by gsantos1979** [CheckPointSW/CloudGuardIaaS#76]
Are any new repository to get amis_url inside amis module?

variable "amis_url" {
  type = string
  description = "URL to amis.json"
  default = "https://s3.amazonaws.com/CloudFormationTemplate/amis.json" => returning Access Denied!!
}

**Comment by chkp-gsudai** [comment]
Hi @gsantos1979  we are working on a fix. Coming soon.

**Comment by chkp-omrina** [comment]
Hi @gsantos1979 we released a fix for the problem.

**Comment by chkp-gsudai** [comment]
issue fixed
