### ISSUE TITLE
Feature request: ha-availability-set-existing-vnet, ha-availability-zones-existing-vnet templates for Azure

### ISSUE THREAD

**Issue by padavrexi** [CheckPointSW/CloudGuardIaaS#77]
Hello,

while there's already a Terraform template for deploying VMSS in existing Azure VNets, no such thing exists for HA availability set/zones. Would it be possible to publish these as it would be **very** helpful for upgrading and migrating from existing deployments.

Thanks,
Nikos

**Comment by Chkp-hadarsh** [comment]
Hi Nikos,
It is indeed possible, we will publish these templates in the next two weeks.

Thanks,
Hadar

**Comment by padavrexi** [comment]
Thanks!

**Comment by chkp-arielto** [comment]
Hi @padavrexi 
As you've requested, we created a new HA template deploying into an existing VNET.
Ariel

**Comment by padavrexi** [comment]
Thanks so much for your fast reaction! It really makes our everyday job easier.
