### ISSUE TITLE
Feature request: Template for SMS deployment

### ISSUE THREAD

**Issue by biderise** [CheckPointSW/CloudGuardIaaS#79]
Hello,

Would it be easy to provide us with the Terraform template for SMS deployment on Azure?

Thanks,
Vangelis

**Comment by Chkp-hadarsh** [comment]
Hi Vangelis,
We will be able to provide it over the next few weeks.

Thanks,
Hadar

**Comment by chkp-arielto** [comment]
Hi @biderise 
The terraform template for SMS is now available.
You can use and deploy it [here](https://github.com/CheckPointSW/CloudGuardIaaS/tree/master/terraform/azure).
Have a good day,
Ariel
