### ISSUE TITLE
Scale Set Multi Zone

### ISSUE THREAD

**Issue by TheOriginalDeadPool** [CheckPointSW/CloudGuardIaaS#88]
In the Terraform scripts:
- vmss-existing-vnet
- vmss-new-vnet

The variable "availability_zones_num" in terraform.tfvars accepts only 1 digit, being 0, 1, 2 or 3.
If you fill in one of these numbers, the scale set will **only** be deployed in that zone.

Azure expects a list of zones where the scale set should be deployed.
My current workaround was to comment out in main.tf the line that states "zones = var.availability_zones_num".
And replace it with " zones = ["1", "2", "3"] ", only then will the scale set be installed as multi-zone.

**Comment by chkp-arielto** [comment]
Hi @TheOriginalDeadPool 
We've added the support in our terraform templates (https://github.com/CheckPointSW/CloudGuardIaaS/pull/90).
Thanks,
Ariel
