### ISSUE TITLE
Create variable for x-chkp-ip-address

### ISSUE THREAD

**Issue by TheOriginalDeadPool** [CheckPointSW/CloudGuardIaaS#89]
Azure > Terraform:
For the following two templates in Azure:
- vmss-new-vnet
- vmss-existing-vnet

Would it be possible to create a variable for x-chkp-ip-address?
And add it as a variable to be filled in the terraform.tfvars?

I would think these would be the required changes (please verify):
In main.tf, modify to:

 tags = var.management_interface == "eth0"?{
    x-chkp-management = var.management_name,
    x-chkp-template = var.configuration_template_name,
    x-chkp-ip-address = **var.x-chkp-ip-address**,
    x-chkp-management-interface = var.management_interface,
    x-chkp-management-address = var.management_IP,
    x-chkp-topology = "eth0:external,eth1:internal",
    x-chkp-anti-spoofing = "eth0:false,eth1:false",
    x-chkp-srcImageUri = "noCustomUri",
  }:{
    x-chkp-management = var.management_name,
    x-chkp-template = var.configuration_template_name,
    x-chkp-ip-address = **var.x-chkp-ip-address**,
    x-chkp-management-interface = var.management_interface,
    x-chkp-topology = "eth0:external,eth1:internal",
    x-chkp-anti-spoofing = "eth0:false,eth1:false",
    x-chkp-srcImageUri = "noCustomUri",
  }
}

In variables.tf add:
variable "x-chkp-ip-address"{
  description = "Define how to manage the Check Point Scale set, from it's ILPIP or Private IP"
  type = string
  default = "private"
}

In terraform.tfvars add:
x-chkp-ip-address           = "PLEASE ENTER public or private"                                     # Fill in "public" or "private" 

Thanks!

**Comment by Chkp-hadarsh** [comment]
Thanks for letting us know, yes we will add the change and publish the updated templates in the next few days.

**Comment by chkp-arielto** [comment]
Hi @TheOriginalDeadPool 
We've added the support in our terraform templates (https://github.com/CheckPointSW/CloudGuardIaaS/pull/90).
Thanks,
Ariel
