### ISSUE TITLE
Terraform deployment modules not idempotent

### ISSUE THREAD

**Issue by Celestica-Edward** [CheckPointSW/CloudGuardIaaS#99]
When using the deployment module for GCP, such as https://github.com/CheckPointSW/CloudGuardIaaS/tree/master/terraform/gcp/high-availability
terraform plan/apply is not idempotent:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # google_compute_address.primary_cluster_ip_ext_address must be replaced
-/+ resource "google_compute_address" "primary_cluster_ip_ext_address" {
      ~ address            = "35.225.34.234" -> (known after apply)
      ~ creation_timestamp = "2021-04-15T13:46:37.978-07:00" -> (known after apply)
      ~ id                 = "projects/gce-infrastructure-sandbox/regions/us-central1/addresses/tf-checkpoint-ha-primary-cluster-address-9a204" -> (known after apply)
      ~ name               = "tf-checkpoint-ha-primary-cluster-address-9a204" -> (known after apply) # forces replacement
      ~ network_tier       = "PREMIUM" -> (known after apply)
      ~ project            = "gce-infrastructure-sandbox" -> (known after apply)
      + purpose            = (known after apply)
      ~ self_link          = "https://www.googleapis.com/compute/v1/projects/gce-infrastructure-sandbox/regions/us-central1/addresses/tf-checkpoint-ha-primary-cluster-address-9a204" -> (known after apply)
      + subnetwork         = (known after apply)
      ~ users              = [] -> (known after apply)
        # (2 unchanged attributes hidden)
    }
```

Steps to reproduce:
Execute terraform apply and create the resources initially. 
Run terraform plan or apply again; it suggests to destroy/recreate the resources. 

This is likely due to the use of uuid() functions: https://github.com/CheckPointSW/CloudGuardIaaS/blob/master/terraform/gcp/high-availability/main.tf#L23

Without idempotency, this makes it difficult to use on platforms like terraform enterprise/cloud, or in general, running terraform plan to see if there's any expected changes if this was embedded with other terraform scripts.

**Comment by Chkp-hadarsh** [comment]
Thanks for notifying us, we will fix it soon and deliver the new templates with this fix.

**Comment by chkp-arielto** [comment]
Hi @Celestica-Edward 
The fix has been delivered [here](https://github.com/CheckPointSW/CloudGuardIaaS/pull/102)
Thanks for sharing!
